
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class IndexView extends javax.swing.JFrame {

    /**
     * Creates new form IndexView
     */
    public IndexView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        indexDesktopPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        contactMenu = new javax.swing.JMenu();
        registerContactMenu = new javax.swing.JMenuItem();
        menuListarUsuarios = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria Controller");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fileinterfacesymboloftextpapersheet_79740.png"))); // NOI18N
        jMenu1.setText("Arquivo");

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit_icon-icons.com_70975.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        contactMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_84308.png"))); // NOI18N
        contactMenu.setText("Contatos");

        registerContactMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adduser_añadir_3553.png"))); // NOI18N
        registerContactMenu.setText("Cadastrar");
        registerContactMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerContactMenuActionPerformed(evt);
            }
        });
        contactMenu.add(registerContactMenu);

        menuListarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/searchmagnifierinterfacesymbol1_79893.png"))); // NOI18N
        menuListarUsuarios.setText("Listar");
        menuListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarUsuariosActionPerformed(evt);
            }
        });
        contactMenu.add(menuListarUsuarios);

        jMenuBar1.add(contactMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indexDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indexDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Deseja mesmo sair?");
        if(confirm == JOptionPane.YES_OPTION){
            this.dispose();
            new LoginView().setVisible(true);
        }
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarUsuariosActionPerformed
        ContactSearchView userSearch = new ContactSearchView(indexDesktopPanel);
        indexDesktopPanel.add(userSearch);
        userSearch.setVisible(true);
    }//GEN-LAST:event_menuListarUsuariosActionPerformed

    private void registerContactMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerContactMenuActionPerformed
        ContactRegisterView registerContact = new ContactRegisterView();
        indexDesktopPanel.add(registerContact);
        registerContact.setVisible(true);
    }//GEN-LAST:event_registerContactMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu contactMenu;
    private javax.swing.JDesktopPane indexDesktopPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuListarUsuarios;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem registerContactMenu;
    // End of variables declaration//GEN-END:variables
}
